/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dwx' at '16-4-21 下午3:45' with Gradle 2.12
 *
 * @author dwx, @date 16-4-21 下午3:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
